### ISSUE TITLE
Traceback when selecting Tools --> SEH Helper

### ISSUE THREAD

**Issue by rickhg12hs** [EliseZeroTwo/SEH-Helper#1]
BN Version:  3.6.4709-dev Personal (715fcd79)

```
[Default] Traceback (most recent call last):
[Default]   File "/home/rick/.binaryninja/repositories/community/plugins/EliseZeroTwo_SEHHelper/__init__.py", line 268, in createPane
[Default]     widget = SEHWidget(context.binaryView, PE(data=data))
[Default]   File "/home/rick/.binaryninja/repositories/community/plugins/EliseZeroTwo_SEHHelper/__init__.py", line 178, in __init__
[Default]     for entry in file.DIRECTORY_ENTRY_EXCEPTION:
[Default] AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_EXCEPTION'. Did you mean: 'DIRECTORY_ENTRY_BASERELOC'?
```

**Comment by EliseZeroTwo** [comment]
I noticed this recently too, I will try to work on it soon
